$ANSIBLE_VAULT;1.1;AES256
38653038616135613932396461366234653161303364363739613132653332363366636631393066
3664633830313437346539623135323766393334643138630a326230376462333763373335313832
32383435316630343963303565633061326561326661616536363764336337373332363534376663
6366613535306263630a313562616230333634316561316662376163393265643064373563323363
64323561393739306632623737323635363630643938393438326539366332323966333936343131
31386531623362333332303739333538376265323532373663333961653961666466376534386137
34643831336230613636343734336261303962636236396464633032306533643634316565396232
36623565326235333237346666626164626235363438366263326261663862353166336462303965
62363539353861323438373830653237343938663435363833363430316435386366383863386238
3838376163313762366334323634646131613765636138333238
